AllCops:
  TargetRubyVersion: 2.2
  Excludes:
    - vendor/**/*
    - bin/**

Documentation:
  # don't require classes to be documented
  Enabled: false

Encoding:
  # no need to always specify encoding
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - grape-markdown.gemspec
    - spec/**/*

Naming/FileName:
  Exclude:
    - lib/grape-markdown.rb

Performance/StringReplacement:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": ()
    "%w": ()
